export const ActionTypes = {
  SET_USER_ANSWERS: "SET_USER_ANSWERS",
  SET_IS_CORRECT: "SET_IS_CORRECT",
  SET_DRAGGED_WORD: "SET_DRAGGED_WORD",
  SET_DISABLED_INPUTS: "SET_DISABLED_INPUTS",
  SET_IS_ANSWER_CORRECT: "SET_IS_ANSWER_CORRECT",
  SET_DATA: "SET_DATA",
  RESET_STATE: "RESET_STATE",
  UPDATE_SINGLE_ANSWER: "UPDATE_SINGLE_ANSWER",
  TOGGLE_INPUT_DISABLED: "TOGGLE_INPUT_DISABLED",
} as const;
